name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add aarch64-linux-android
      - run: cargo install cargo-ndk
      - run: cargo test --verbose
      - run: cargo ndk -t arm64-v8a build --release
      - uses: actions/upload-artifact@v4
        with:
          name: mint-android-aarch64
          path: target/aarch64-linux-android/release/mint
