name: rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --verbose
  build:
    needs: [test]
    strategy:
      matrix:
        targets:
          - name: linux-x86_64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
          - name: windows-x86_64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: ".exe"
          - name: android-aarch64
            runner: ubuntu-latest
            target: aarch64-linux-android
            suffix: ""
    runs-on: ${{ matrix.targets.runner }}
    steps:
      - uses: actions/checkout@v4

      # get git rev
      - if: runner.os != 'Windows'
        run: echo "REV_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - if: runner.os == 'Windows'
        run: echo "REV_SHORT=$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV

      - run: rustup target add ${{ matrix.targets.target }}

      - if: ${{ matrix.targets.name == 'android-aarch64' }}
        run: cargo install cargo-ndk
      - if: ${{ matrix.targets.name == 'android-aarch64' }}
        run: cargo ndk -t arm64-v8a build --release

      - if: ${{ matrix.targets.name != 'android-aarch64' }}
        run: cargo build --release --target ${{ matrix.targets.target }} -p mint

      - uses: actions/upload-artifact@v4
        with:
          name: mint-${{ matrix.targets.name }}-${{ env.REV_SHORT }}
          path: target/${{ matrix.targets.target }}/release/mint${{ matrix.targets.suffix}}
