name: rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --verbose
  # instead of using a big matrix and conditional steps, this is clearer
  build-linux:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]
        package: [mint]
    env:
      target: ${{ matrix.arch }}-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - run: echo "GIT_REV_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: rustup target add ${{ env.target }}
      - run: cargo build --release --target ${{ env.target }} -p ${{ matrix.package }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-linux-${{ matrix.arch }}-${{ env.GIT_REV_SHORT }}
          path: target/${{ env.target }}/release/${{ matrix.package }}
  build-windows:
    needs: [test]
    runs-on: windows-latest
    env:
      target: x86_64-pc-windows-msvc
      package: mint
    steps:
      - uses: actions/checkout@v4
      # note: this step is a little different on windows
      - run: echo "GIT_REV_SHORT=$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV
      - run: rustup target add ${{ env.target }}
      - run: cargo build --release --target ${{ env.target }} -p ${{ env.package }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.package }}-windows-x86_64-${{ env.GIT_REV_SHORT }}
          path: target/${{ env.target }}/release/${{ env.package }}.exe
  build-android:
    needs: [test]
    runs-on: ubuntu-latest
    env:
      target: aarch64-linux-android
      package: mint
    steps:
      - uses: actions/checkout@v4
      - run: echo "GIT_REV_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: rustup target add ${{ env.target }}
      - run: cargo install cargo-ndk
      - run: cargo ndk -t ${{ env.target }} build --release - p ${{ env.package }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.package }}-android-aarch64-${{ env.GIT_REV_SHORT }}
          path: target/${{ env.target }}/release/${{ env.package }}
