name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        targets:
          - name: linux-x86_64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
          - name: windows-x86_64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: ".exe"
          - name: android-aarch64
            runner: ubuntu-latest
            target: aarch64-linux-android
            suffix: ""
    runs-on: ${{ matrix.targets.runner }}
    steps:
      - uses: actions/checkout@v4
      - run: echo $ANDROID_NDK_HOME
      - run: rustup target add ${{ matrix.targets.target }}
      - run: cargo test --verbose
      - name: Build mint release
        run: cargo build --release --target ${{ matrix.targets.target}} -p mint
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: mint-${{ matrix.targets.name }}
          path: target/${{ matrix.targets.target }}/release/mint${{ matrix.targets.suffix}}
